### ISSUE TITLE
Server dosn*t start in new LB3 Installation

### ISSUE THREAD

**Issue by patrick-dmxc** [LoxYourLife/loxberry-express#7]
Hi, i did e new clean Instalation of LB3 and instaleed the latest Express-Server, but it dosn't start.

![Screenshot 2023-03-26 193541](https://user-images.githubusercontent.com/7863301/227793700-be1981ad-c8a7-4cd4-802c-2eb991287100.png)

**Comment by Scyks** [comment]
Hey and thanks for reporting this issue.

Could you provide the content of all the log files from your loxberry under `logs/plugins/express`.
Especially the 2 manger log files.

Thanks

**Comment by patrick-dmxc** [comment]
This is all i found

[express.log](https://github.com/LoxYourLife/loxberry-express/files/11129577/express.log)
![image](https://user-images.githubusercontent.com/7863301/229290751-a81078ab-e08c-452a-8536-14814812b0a7.png)
![image](https://user-images.githubusercontent.com/7863301/229290778-9daa5844-7b50-4f7b-877a-bf0731be116b.png)

**Comment by Scyks** [comment]
You should have something like this: 
<img width="1480" alt="image" src="https://user-images.githubusercontent.com/875242/229292656-29daa082-e9dd-4d05-a6d7-a648e8f48d1e.png">


Can you try to reinstall the newest version?

**Comment by patrick-dmxc** [comment]
Reinstall did not helped

and the Logs dont appeare in More Logfiles....

**Comment by patrick-dmxc** [comment]
I did a clean new vanilla installation of Loxberry 3 now, and only installed the Express Server.
Same issue ......

Running it in a VM on Unraid

**Comment by patrick-dmxc** [comment]
Nothing?
